apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170074230
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170074230
    app.kubernetes.io/part-of: test-app-170074230
  name: java-quarkus-170074230
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170074230
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170074230
    spec:
      containers:
      - image: quay.io/hacdev/xva8anog-tenant/test-app-170074230/java-quarkus-170074230@sha256:87e27f425c28f60d44d29dac7de24aaae5f406084b9b5611322a03f3a0c0dc8d
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
