apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-170074230
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/xva8anog-tenant/test-app-170074230/java-quarkus-170074230@sha256:87e27f425c28f60d44d29dac7de24aaae5f406084b9b5611322a03f3a0c0dc8d
        name: my-java-quarkus
        resources: {}
status: {}
